#!/bin/bash
#
# Download mainline kernel ppa packages published by the Ubuntu kernel team.
#
# usage: kernel-ppa list
#        kernel-ppa get [rc|daily|<version>]
#        kernel-ppa install
#
#

BASEURL="http://kernel.ubuntu.com/~kernel-ppa/mainline"

usage() {
    echo "usage: kernel-ppa list"
    echo "       kernel-ppa get [rc|daily|<version>]"
    echo "       sudo kernel-ppa install"
}

list_versions() {
    wget -q -O - "$BASEURL/?C=N;O=D" |
        perl -lane 'print $1 if /href="(v[^"]+)"/' |
        sed 's@/$@@'
}

get_packages() {
    arch=`uname -m | sed s/x86_64/amd64/`

    case "$1" in
    rc|"") version=`list_versions | head -1` ;;
    daily) version=`date "+daily/%Y-%m-%d"` ;;
    *)     version="$1" ;;
    esac

    wget \
    --no-verbose \
    --recursive \
    --execute robots=off \
    --no-parent \
    --no-directories \
    --no-clobber \
    --accept "*_all.deb,*_${arch}.deb" \
    --reject "*lowlatency*.deb" \
    "${BASEURL}/${version}/"
}

install_packages() {
    files=$(echo linux-*.deb)
    if [ "$files" = "linux-*.deb" ]; then
        echo "Run 'kernel-ppa get' first."
    else
	echo "Installing $files"
        DEBIAN_FRONTEND=noninteractive dpkg --install $files
    fi
}

case "$1" in
help)    usage ;;
list)    list_versions ;;
get)     get_packages "$2" ;;
install) install_packages ;;
*)
    usage
    exit 1
    ;;
esac
