#!/bin/bash

ssh_user=$USER
ssh_opts="
-o UserKnownHostsFile=/dev/null
-o StrictHostKeyChecking=no
-o LogLevel=ERROR
"

ARGS=$(getopt -o -l: -n virt-ssh -- "$@")
eval set -- "$ARGS"
while :; do
    case "$1" in
    -l) ssh_user=$2; shift 2 ;;
    --) shift; break ;;
    *)  vmname=$1; shift; break
    esac
done
if [ -z $vmname ]; then
    echo "usage: virt-ssh [-l <user>] <domain>" >&2
    exit 1
fi

vmaddr=`virt-addr $vmname`
if [ -z $vmaddr ]; then
    echo "Failed to get address of '$vmname'."
    exit 1
fi

exec ssh $ssh_opts -l $ssh_user $vmaddr
