#!/bin/sh

ARGS=$(getopt -o mn:i: --long macaddr,network:,index: -n virt-addr -- "$@")

if [ $? -ne 0 -o -z "$1" ]; then
	echo "usage: $0: [--network <network>] [--index <index>] [--macaddr] <name>" >&2
	exit 2
fi

eval set -- "$ARGS"

while :; do
	case "$1" in
		-n|--network)
			LIBVIRT_NETWORK=$2
			shift 2
			;;

		-i|--index)
			INTERFACE_INDEX=$2
			shift 2
			;;
		-m|--macaddr)
			ONLY_MACADDR=1
			shift
			;;
		--)	shift
			break
			;;

		-*)	echo "ERROR: unimplemented option: $1" >&2
			exit 2
			;;
	esac
done

: ${LIBVIRT_NETWORK:=default}
: ${INTERFACE_INDEX:=1}

dom_name=$1
shift

macaddr=$(virsh dumpxml $dom_name | 
	xmllint --xpath "string((//interface/mac/@address)[${INTERFACE_INDEX}])" -)

if [ "$ONLY_MACADDR" = 1 ]; then
	echo $macaddr
	exit
fi

# 1. Get the lease info for macaddr.
# 2. Remove the 2 line header.
# 3. Remove the trailing blank line.
# 4. Grab the ip address field; e.g. 192.168.122.118/24
# 5. Trim the CIDR subnet; e.g. /24
virsh net-dhcp-leases ${LIBVIRT_NETWORK} --mac $macaddr |
  sed '1,2d' |
  grep -v '^$' |
  awk '{print $5}' |
  sed 's@/[0-9]*@@'
